# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LocationWatch' do
pod 'Alamofire'
pod 'AlamofireImage', '~> 2.0'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
end

target 'LocationWatch WatchKit App' do

end

target 'LocationWatch WatchKit Extension' do

end

